const env = "production";
// const env = "";
export const url =
  env === "production"
    ? "https://new-daraz-clone.herokuapp.com"
    : "http://localhost:5000";

export const top100Films = [
  { label: "FRAKIN Kitchen Washing Hand cleaning Gloves waterproof gloves" },
  { label: "AlClean House Hold Gloves Rubber Multiuse Washing Cleaning" },
  { label: "PACK OF 2 - Disposable gloves 200 pieces Powder Free Polythene" },
  { label: "cleaninggloves" },
  {
    label:
      "Dishwashing Cleaning Gloves Magic Silicone Rubber Dish Washing Glove",
  },
  { label: "Extra Long Washing Gloves Cleaning Warm Waterproof Rubber Glove" },
  { label: "300 Pcs Gloves Polythene Disposable Restaurant Garden Kitchen" },
  { label: "abc" },
  { label: "Nokiya 3310" },
  { label: "Nokiya set 4520" },
  { label: "Samsung new phone" },
  { label: "keypad small samsung" },
  { label: "4G keypad cell phone" },
  { label: "smart phons" },
  { label: "pressurewashers new item" },
  { label: "hyndiya pressure washer" },
  { label: "new pressure washe" },
  { label: "135 bar-Hyundai Car Pressure" },
  { label: "136 car pressure washer" },
  {
    label: "hplink",
  },
  { label: "fire sd card" },
  { label: "Samsung 64 sdcard" },
  { label: "Lexsar sdcards" },
  { label: "mini card" },
  { label: "hp cards" },
  { label: "micro best card" },
  { label: "mini litle card" },
  { label: "mini 136 hp card" },
  { label: "famous paintguns" },
  { label: "gun water" },
  { label: "taptal paintguns" },
  { label: "drybox best openion" },
  { label: "Nangrow drybox " },
  { label: "drybox leavel 5" },
  { label: "drybox cream" },
  { label: "garlictools level1" },
  { label: "The Intouchables" },
  { label: "garlictools level 3" },
  { label: "garlictools level 4" },
  { label: "featurephone one" },
  { label: "featurephone level 2" },
  { label: "featurephone samsung" },
  { label: "alaramclocks new 1" },
  { label: "alaramclocks timerr" },
  { label: "alaramclocks set new" },
  { label: "kidswears new item" },
  { label: "kidswears new shirt" },
  { label: "kidswears yellow label" },
  { label: '"kidswears team  shirts' },
  { label: "kidswears new children shirts" },
  { label: "beautiful pencils" },
  { label: "new hero pencil" },
  {
    label: "Golden pencils",
  },
  { label: "The Great Dictator", year: 1940 },
  { label: "Cinema Paradiso", year: 1988 },
  { label: "The Lives of Others", year: 2006 },
  { label: "Grave of the Fireflies", year: 1988 },
  { label: "Paths of Glory", year: 1957 },
  { label: "Django Unchained", year: 2012 },
  { label: "The Shining", year: 1980 },
  { label: "WALL·E" },
  { label: "American Beauty" },
  { label: "The Dark Knight Rises", year: 2012 },
  { label: "Princess Mononoke" },
  { label: "Aliens", year: 1986 },
  { label: "Oldboy", year: 2003 },
  { label: "Once Upon a Time in America", year: 1984 },
  { label: "Witness for the Prosecution", year: 1957 },
  { label: "Das Boot" },
  { label: "Citizen Kane", year: 1941 },
  { label: "North by Northwest", year: 1959 },
  { label: "Vertigo", year: 1958 },
  {
    label: "Star Wars: Episode VI - Return of the Jedi",
    year: 1983,
  },
  { label: "Reservoir Dogs", year: 1992 },
  { label: "Braveheart" },
  { label: "M" },
  { label: "Requiem for a Dream" },
];
